#!/bin/sh
test -n "$GANETI_NODE_NAME" || exit 0
GANETI_NODE_HOSTNAME=`echo $GANETI_NODE_NAME|cut -d'.' -f 1`
if [ "$GANETI_MASTER" = "`hostname`" ]; then
  # Add node to known_hosts
  touch /etc/sci/known_hosts
  ssh-keyscan -t rsa,dsa $GANETI_NODE_HOSTNAME 2>&1 | sort -u - /etc/sci/known_hosts > /etc/sci/tmp_hosts
  cat /etc/sci/tmp_hosts > /etc/sci/known_hosts
  ip=`ssh -o GlobalKnownHostsFile=/etc/sci/known_hosts -o UserKnownHostsFile=/etc/sci/known_hosts $GANETI_NODE_HOSTNAME lan-ip`
  echo "$ip	$GANETI_NODE_HOSTNAME-lan.`hostname -d` $GANETI_NODE_HOSTNAME-lan" >> /etc/hosts
  # deploy files
  gnt-cluster copyfile /etc/hosts
fi
