#!/bin/sh

if [ -e /var/lib/ganeti/rapi/users ]; then
	echo `cat /var/lib/ganeti/rapi/users|grep scweb|awk '{print $2}'`|htpasswd -i -c /etc/sci/sci-mond.htpasswd sci-mond
	invoke-rc.d nginx restart||true
fi

