#!/bin/sh

if [ -e /opt/sci-web/sci_webinterface/settings.py ]; then
	sed -i "s/vncpassword/`cat /etc/ganeti/vnc-cluster-password|awk '{print $1}'`/" /opt/sci-web/sci_webinterface/settings.py
	invoke-rc.d uwsgi restart||true
fi

